/*
 *
 * Cart constants
 *
 */

import { createActionType } from 'utils/reduxHelper';

export const CONTEXT = 'ISALON/CART';
export const GET_CART = `${CONTEXT}/GET_CART`;
export const REMOVE_CART_ITEM = `${CONTEXT}/REMOVE_CART_ITEM`;
export const ADD_PRODUCT_ITEM = `${CONTEXT}/ADD_PRODUCT_ITEM`;
export const REMOVE_PRODUCT_ITEM = `${CONTEXT}/REMOVE_PRODUCT_ITEM`;
export const SELECT_CART_ITEM = `${CONTEXT}/SELECT_CART_ITEM`;
export const SELECT_ALL_CART_ITEMS = `${CONTEXT}/SELECT_ALL_CART_ITEMS`;
export const SELECT_ADDRESS = `${CONTEXT}/SELECT_ADDRESS`;
export const GET_CART_QUANTITY = `${CONTEXT}/GET_CART_QUANTITY`;
export const SHOW_ERROR = `${CONTEXT}/SHOW_ERROR`;
export const LIKE_PRODUCT = `${CONTEXT}/LIKE_PRODUCT`;
export const UNLIKE_PRODUCT = `${CONTEXT}/UNLIKE_PRODUCT`;
export const CALCULATE_CART = `${CONTEXT}/CALCULATE_CART`;
export const CLEAR_CART_VIEW = `${CONTEXT}/CLEAR_CART_VIEW`;

export const [
  GET_CART_REQUEST,
  GET_CART_SUCCESS,
  GET_CART_FAIL,
] = createActionType(GET_CART);

export const [
  REMOVE_CART_ITEM_REQUEST,
  REMOVE_CART_ITEM_SUCCESS,
  REMOVE_CART_ITEM_FAIL,
] = createActionType(REMOVE_CART_ITEM);

export const [
  ADD_PRODUCT_ITEM_REQUEST,
  ADD_PRODUCT_ITEM_SUCCESS,
  ADD_PRODUCT_ITEM_FAIL,
] = createActionType(ADD_PRODUCT_ITEM);

export const [
  REMOVE_PRODUCT_ITEM_REQUEST,
  REMOVE_PRODUCT_ITEM_SUCCESS,
  REMOVE_PRODUCT_ITEM_FAIL,
] = createActionType(REMOVE_PRODUCT_ITEM);

export const [
  SELECT_CART_ITEM_REQUEST,
  SELECT_CART_ITEM_SUCCESS,
  SELECT_CART_ITEM_FAIL,
] = createActionType(SELECT_CART_ITEM);

export const [
  SELECT_ALL_CART_ITEMS_REQUEST,
  SELECT_ALL_CART_ITEMS_SUCCESS,
  SELECT_ALL_CART_ITEMS_FAIL,
] = createActionType(SELECT_ALL_CART_ITEMS);

export const [
  GET_CART_QUANTITY_REQUEST,
  GET_CART_QUANTITY_SUCCESS,
  GET_CART_QUANTITY_FAIL,
] = createActionType(GET_CART_QUANTITY);

export const [
  LIKE_PRODUCT_REQUEST,
  LIKE_PRODUCT_SUCCESS,
  LIKE_PRODUCT_FAIL,
] = createActionType(LIKE_PRODUCT);

export const [
  UNLIKE_PRODUCT_REQUEST,
  UNLIKE_PRODUCT_SUCCESS,
  UNLIKE_PRODUCT_FAIL,
] = createActionType(UNLIKE_PRODUCT);

export const [
  CALCULATE_CART_REQUEST,
  CALCULATE_CART_SUCCESS,
  CALCULATE_CART_FAIL,
] = createActionType(CALCULATE_CART);
