/*
 *
 * FavoritePage constants
 *
 */

import { createActionType } from 'utils/reduxHelper';

export const CONTEXT = 'ISALON/FAVORITE';
export const GET_FAVORITED_SALONS = `${CONTEXT}/GET_FAVORITED_SALONS`;
export const REMOVE_FAVORITED_SALON = `${CONTEXT}/REMOVE_FAVORITED_SALON`;
export const REMOVE_FAVORITED_SHOWCASE = `${CONTEXT}/REMOVE_FAVORITED_SHOWCASE`;
export const GET_FAVORITED_PRODUCTS = `${CONTEXT}/GET_FAVORITED_PRODUCTS`;
export const REMOVE_FAVORITED_PRODUCT = `${CONTEXT}/REMOVE_FAVORITED_PRODUCT`;

export const [
  GET_FAVORITED_SALONS_REQUEST,
  GET_FAVORITED_SALONS_SUCCESS,
  GET_FAVORITED_SALONS_FAIL,
] = createActionType(GET_FAVORITED_SALONS);

export const [
  REMOVE_FAVORITED_SALON_REQUEST,
  REMOVE_FAVORITED_SALON_SUCCESS,
  REMOVE_FAVORITED_SALON_FAIL,
] = createActionType(REMOVE_FAVORITED_SALON);

export const [
  REMOVE_FAVORITED_SHOWCASE_REQUEST,
  REMOVE_FAVORITED_SHOWCASE_SUCCESS,
  REMOVE_FAVORITED_SHOWCASE_FAIL,
] = createActionType(REMOVE_FAVORITED_SHOWCASE);

export const [
  GET_FAVORITED_PRODUCTS_REQUEST,
  GET_FAVORITED_PRODUCTS_SUCCESS,
  GET_FAVORITED_PRODUCTS_FAIL,
] = createActionType(GET_FAVORITED_PRODUCTS);

export const [
  REMOVE_FAVORITED_PRODUCT_REQUEST,
  REMOVE_FAVORITED_PRODUCT_SUCCESS,
  REMOVE_FAVORITED_PRODUCT_FAIL,
] = createActionType(REMOVE_FAVORITED_PRODUCT);
