/*
 *
 * BookingHistoryPage constants
 *
 */

import { createActionType } from 'utils/reduxHelper';

export const CONTEXT = 'ISALON/BOOKING_HISTORY';

export const GET_BOOKING_HISTORY = `${CONTEXT}/GET_BOOKING_HISTORY`;
export const SHOW_BOOKING_HISTORY_DETAIL = `${CONTEXT}/SHOW_BOOKING_HISTORY_DETAIL`;
export const HIDE_BOOKING_HISTORY_DETAIL = `${CONTEXT}/HIDE_BOOKING_HISTORY_DETAIL`;
export const CANCEL_BOOKING_ORDER = `${CONTEXT}/CANCEL_BOOKING_ORDER`;

export const [
  GET_BOOKING_HISTORY_REQUEST,
  GET_BOOKING_HISTORY_SUCCESS,
  GET_BOOKING_HISTORY_FAIL,
] = createActionType(GET_BOOKING_HISTORY);

export const [
  CANCEL_BOOKING_ORDER_REQUEST,
  CANCEL_BOOKING_ORDER_SUCCESS,
  CANCEL_BOOKING_ORDER_FAIL,
] = createActionType(CANCEL_BOOKING_ORDER);
