/*
 *
 * ProductSearch constants
 *
 */

import { createActionType } from 'utils/reduxHelper';

export const CONTEXT = 'ISALON/PRODUCT_SEARCH';

export const GET_SEARCH_HISTORY = `${CONTEXT}/GET_SEARCH_HISTORY`;
export const CLEAR_SEARCH_HISTORY = `${CONTEXT}/CLEAR_SEARCH_HISTORY`;
export const GET_HOT_KEYWORDS = `${CONTEXT}/GET_HOT_KEYWORDS`;
export const GET_SUGGESTION_KEYWORDS = `${CONTEXT}/GET_SUGGESTION_KEYWORDS`;

export const [
  GET_SEARCH_HISTORY_REQUEST,
  GET_SEARCH_HISTORY_SUCCESS,
  GET_SEARCH_HISTORY_FAIL,
] = createActionType(GET_SEARCH_HISTORY);

export const [
  CLEAR_SEARCH_HISTORY_REQUEST,
  CLEAR_SEARCH_HISTORY_SUCCESS,
  CLEAR_SEARCH_HISTORY_FAIL,
] = createActionType(CLEAR_SEARCH_HISTORY);

export const [
  GET_HOT_KEYWORDS_REQUEST,
  GET_HOT_KEYWORDS_SUCCESS,
  GET_HOT_KEYWORDS_FAIL,
] = createActionType(GET_HOT_KEYWORDS);

export const [
  GET_SUGGESTION_KEYWORDS_REQUEST,
  GET_SUGGESTION_KEYWORDS_SUCCESS,
  GET_SUGGESTION_KEYWORDS_FAIL,
] = createActionType(GET_SUGGESTION_KEYWORDS);
