/*
 *
 * NotificationList constants
 *
 */

import { createActionType } from 'utils/reduxHelper';

export const CONTEXT = 'ISALON/NOTIFICATIONS';

export const GET_NOTIFICATIONS = `${CONTEXT}/GET_NOTIFICATIONS`;
export const MARK_AS_READ_NOTIFICATION = `${CONTEXT}/MARK_AS_READ_NOTIFICATION`;
export const GET_NOTIFICATION_COUNT = `${CONTEXT}/GET_NOTIFICATION_COUNT`;
export const DELETE_NOTIFICATION = `${CONTEXT}/DELETE_NOTIFICATION`;
export const GET_MY_SHOP_NOTIFICATIONS = `${CONTEXT}/GET_MY_SHOP_NOTIFICATIONS`;
export const GET_SYSTEM_SHOP_NOTIFICATIONS = `${CONTEXT}/GET_SYSTEM_SHOP_NOTIFICATIONS`;
export const GET_SHOP_NOTIFICATION_COUNT = `${CONTEXT}/GET_SHOP_NOTIFICATION_COUNT`;
export const GET_COIN_NOTIFICATIONS = `${CONTEXT}/GET_COIN_NOTIFICATIONS`;

export const [
  GET_NOTIFICATION_COUNT_REQUEST,
  GET_NOTIFICATION_COUNT_SUCCESS,
  GET_NOTIFICATION_COUNT_FAIL,
] = createActionType(GET_NOTIFICATION_COUNT);

export const [
  GET_NOTIFICATIONS_REQUEST,
  GET_NOTIFICATIONS_SUCCESS,
  GET_NOTIFICATIONS_FAIL,
] = createActionType(GET_NOTIFICATIONS);

export const [
  MARK_AS_READ_NOTIFICATION_REQUEST,
  MARK_AS_READ_NOTIFICATION_SUCCESS,
  MARK_AS_READ_NOTIFICATION_FAIL,
] = createActionType(MARK_AS_READ_NOTIFICATION);

export const [
  DELETE_NOTIFICATION_REQUEST,
  DELETE_NOTIFICATION_SUCCESS,
  DELETE_NOTIFICATION_FAIL,
] = createActionType(DELETE_NOTIFICATION);

export const [
  GET_MY_SHOP_NOTIFICATIONS_REQUEST,
  GET_MY_SHOP_NOTIFICATIONS_SUCCESS,
  GET_MY_SHOP_NOTIFICATIONS_FAIL,
] = createActionType(GET_MY_SHOP_NOTIFICATIONS);

export const [
  GET_SYSTEM_SHOP_NOTIFICATIONS_REQUEST,
  GET_SYSTEM_SHOP_NOTIFICATIONS_SUCCESS,
  GET_SYSTEM_SHOP_NOTIFICATIONS_FAIL,
] = createActionType(GET_SYSTEM_SHOP_NOTIFICATIONS);

export const [
  GET_SHOP_NOTIFICATION_COUNT_REQUEST,
  GET_SHOP_NOTIFICATION_COUNT_SUCCESS,
  GET_SHOP_NOTIFICATION_COUNT_FAIL,
] = createActionType(GET_SHOP_NOTIFICATION_COUNT);

export const [
  GET_COIN_NOTIFICATIONS_REQUEST,
  GET_COIN_NOTIFICATIONS_SUCCESS,
  GET_COIN_NOTIFICATIONS_FAIL,
] = createActionType(GET_COIN_NOTIFICATIONS);
