export default {
  CURRENT_USER: 'loggedInUser',
  OAUTH_TOKEN: 'token',
  OAUTH_TOKEN_LEGACY: 'token_legacy',
  OAUTH_REFRESH_TOKEN: 'refresh_token',
  TOKEN_EXPIRE_TIME: 'expires',
  SALON_BOOKING: 'salon_booking',
  LOCATION: 'currentLocation',
  PROVINCES: 'provinces',
  UUID: 'uuid',
  APP_INTRO: 'app_intro',
  SEARCH_HISTORY: 'search_history',
  VIEWED_PRODUCTS: 'viewed_products',
  SEARCH_CONFIGS: 'search_configs',
  CURRENT_VERSION: 'current_version',
  AFFILIATE_TOKEN: 'affiliate_token',
  SETTINGS: 'settings',
  POPUP: 'popup',
};
